name: udd-update-dependencies

on:
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Update dependencies
        run: |
          deno run -A https://deno.land/x/udd/main.ts import_map.json deps.ts dev_deps.ts examples/**/import_map.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: pr
        with:
          commit-message: "Update dependencies"
          title: Update dependencies
          body: >
            Dependencies updated by [udd](https://github.com/hayd/deno-udd).

            *To run other CI actions close/reopen this PR*
          branch: dependencies
          author: GitHub <noreply@github.com>
          delete-branch: true
      - name: Retrieve PR number
        id: pr_num
        run: echo "::notice ::PR_NUM=${{ env.PULL_REQUEST_NUMBER }}"
